name: 'Post-Check'
description: 'Post Step After Check, eg. comment, add reviewers'
inputs:
  comment-file:
    description: 'comment file path'
    required: true
    default: ''
  reviewers:
    description: 'reviewers'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: ${{ inputs.comment-file }}
    - name: Add Reviewers to PR
      uses: ryaugusta/pr-add-reviewers-action@v1
      with:
        token: ${{ github.token }}
        reviewers: ${{ inputs.reviewers }}